apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: workflows-dev
  name: hap-nidd-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      component: hap-nidd-worker
      type: ray
  template:
    metadata:
      labels:
        component: hap-nidd-worker
        type: ray
    spec:
      securityContext:
        fsGroup: 1000660000
        runAsUser: 1000660000

      restartPolicy: Always

      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
        - name: hap-nidd
          # MIKE: replace the base image with your Dockerfile_gpu but DO NOT include HAP models in the image
          image: docker.io/rayproject/ray:latest-py310-gpu
          imagePullPolicy: IfNotPresent
          command:  [ "/bin/bash"]
          args: ["-c", "ray start --num-cpus=4 --address=$HAP_NIDD_SERVICE_HOST:$HAP_NIDD_SERVICE_PORT_REDIS_PRIMARY --block"]
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          resources:
            requests:
              cpu: 4
              memory: 16Gi
            limits:
              cpu: 4
              memory: 16Gi
      imagePullSecrets:
      - name: all-icr-io
