# Ray head node service, allowing worker pods to discover the head node.
apiVersion: v1
kind: Service
metadata:
  namespace: workflows-dev
  name: hap-nidd
spec:
  type: NodePort
  ports:
    # Redis ports.
    - name: redis-primary
      port: 6379
      targetPort: 6379
    - name: redis-shard-0
      port: 6380
      targetPort: 6380
    - name: redis-shard-1
      port: 6381
      targetPort: 6381
    - name: dashboard
      nodePort: 32000
      port: 8265
      targetPort: 8265

  selector:
    component: hap-nidd-head-node
