apiVersion: v1
kind: ServiceAccount
metadata:
  name: codeflare-kfp-svcaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: codeflare-kfp-role
rules:
  - apiGroups: ["apps",""]
    resources: ["pods", "deployments", "configmaps", "routes", "services", "endpoints", "apps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codeflare-kfp-binding
subjects:
  - kind: ServiceAccount
    name: codeflare-kfp-svcaccount
roleRef:
  kind: Role
  name: codeflare-kfp-role
  apiGroup: rbac.authorization.k8s.io
